a = int(input(f"Digite o numero para saber o valor da tabuada: "))
print(f"-"*12)
print(f"{a} * {1:2} = {a*1}")
print(f"{a} * {2:2} = {a*2}")
print(f"{a} * {3:2} = {a*3}")
print(f"{a} * {4:2} = {a*4}")
print(f"{a} * {5:2} = {a*5}")
print(f"{a} * {6:2} = {a*6}")
print(f"{a} * {7:2} = {a*7}")
print(f"{a} * {8:2} = {a*8}")
print(f"{a} * {9:2} = {a*9}")
print(f"{a} * {10:2} = {a*10}")
print(f"-"*12)