a = str(input()).strip()
b = a.replace(" ","")
c = a.split()
print(f"{a.upper()}")
print(f"{a.lower()}")
print(f"{len(b)}")
print(f"{c[0]}")
print(f"{len(c[0])}")
print(f"{c[-1]}")
print(f"{len(c[-1])}")